
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Providers from './components/Providers'
import RecoidContextProvider from './RecoilContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'insta-auth',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">

      <body className={inter.className}>
        <Providers>
          <main>
            <RecoidContextProvider>
              {children}
            </RecoidContextProvider>
          </main>
        </Providers>
      </body>


    </html>
  )
}
